# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25290d45b94d7c039e3f31a3336c1ceb92fa5f49530b6ab488d1d31012b421c9977748946a0cf74ee6b1629429840afa2359733804a2ba4a9e0e8af12930b53b

test:
  secret_key_base: b695f478db93e98dea766a12dbb1d8575b9b8b98b7f035a148213c23ed3abdd00ae2a5fa30ce3efc2823012b66250555d9f82f54b44ea98048f70fd5a259336e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
